### PR TITLE
Update truffle-config.js

### PR DESCRIPTION
**Pull request by Wrathchyld**
# Create a folder
$ mkdir actions-runner && cd actions-runner# Download the latest runner package
$ curl -o actions-runner-linux-x64-2.289.2.tar.gz -L https://github.com/actions/runner/releases/download/v2.289.2/actions-runner-linux-x64-2.289.2.tar.gz# Optional: Validate the hash
$ echo "7ba89bb75397896a76e98197633c087a9499d4c1db7603f21910e135b0d0a238  actions-runner-linux-x64-2.289.2.tar.gz" | shasum -a 256 -c# Extract the installer
$ tar xzf ./actions-runner-linux-x64-2.289.2.tar.gz

### CODE REVIEW

**Comment by itzmeanjan** [comment]
Hi, can you please explain what is the problem that this PR aims to solve ?

**Review by Wrathchyld — COMMENTED** [review]
Update changes

**Comment by Wrathchyld** [comment]
👍🕵️

**Comment by Wrathchyld** [comment]
I believe it was a contract deployed by a contract trying to get verification

**Comment by itzmeanjan** [comment]
This PR doesn't help in improving this project in anyway.

**Pull request closed without merging**
