### PR TITLE
Update and rename ci.yml to ci.yml Jerry Robertson

### PR DESCRIPTION
**Pull request by Wrathchyld**

### CODE REVIEW

**Review by Wrathchyld — COMMENTED** [review]
Just requesting changes

**Comment by itzmeanjan** [comment]
Hi, can you please explain what issue this PR is trying to solve ?

**Comment by Wrathchyld** [comment]
🕵️👍

**Comment by itzmeanjan** [comment]
Closing, as it doesn't help the project in any visible way.

**Pull request closed without merging**
